version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: voyager-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: voyager
      MYSQL_DATABASE: voyager_db
      MYSQL_USER: voyager_user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: